spring:
  data:
    mongodb:
      database: osim-backup
      uri: mongodb://mongodb-osimosimdev:dYVNK1YaknijEKg1N2pNctOT6QkZXBMQXBynUrMgDHcewUXQe90FmJ2TIl65DuHuG5jETLgNxudpfNJhnToTYg==@mongodb-osimosimdev.documents.azure.com:10255/?ssl=true